FROM bitwalker/alpine-elixir:1.5.2

ENV APPSIGNAL_BUILD_FOR_MUSL=1
ENV MIX_ENV=prod
RUN mkdir /build && mkdir /data
RUN apk --update upgrade && apk add --no-cache build-base curl

WORKDIR /build
COPY . .
RUN mix deps.get && mix compile && mix release --env=prod

FROM alpine:edge
ENV APPSIGNAL_BUILD_FOR_MUSL=1
RUN apk --update upgrade && apk add --update --no-cache ncurses-libs libssl1.0 bash
WORKDIR /app
COPY --from=0 /build/releases .
CMD ["/bin/bash /app/foobar/releases/1.0.0/foobar.sh foreground"]