# docker build --file NewDockerfile -t new-elixir .
# docker container run -i elixir-docker-guide
# docker exec -it docker-guide-container sh

FROM designone-prod-stage as build

COPY . .
RUN mix deps.get && mix release

# ------------------------------------------

FROM designone-prod-build
#Copy and extract .tar.gz Release file from the previous stage
COPY --from=build /build/_build/prod/rel/clock/ .

ENTRYPOINT ["/opt/app/bin/clock"]
CMD ["foreground"]
