# Pulls Ubuntu base with elixir pre-installed.
# docker build -t designone-dev -f Dockerfile-Dev .
# docker container run -it --name web-testing designone-dev bash
# docker exec -it discuss-dev bash

FROM elixir:1.5.2

# Install curl and inotify-tools (for phoenix)
RUN apt-get update && apt-get install -y \
    curl \
    inotify-tools \
    && rm -rf /var/lib/apt/lists/*

# Install node and nvm
ENV HOME_INSTALL /installed
ENV NVM_DIR $HOME_INSTALL/nvm
ENV NODE_VERSION 7.5.0
ENV NODE_PATH $NVM_DIR/versions/node/v$NODE_VERSION/lib/node_modules
ENV PATH      $NVM_DIR/versions/node/v$NODE_VERSION/bin:$PATH

# Install Elixir's rebar, hex, and phoenix
RUN mix local.rebar --force \
    && mix local.hex --force \
    && mix archive.install https://github.com/phoenixframework/archives/raw/master/phoenix_new-1.2.5.ez --force


# Install Phoenix Framework
RUN curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.0/install.sh | bash \
    && . $NVM_DIR/nvm.sh \
    && nvm install $NODE_VERSION \
    && nvm alias default $NODE_VERSION \
    && nvm use default
# Specify phoenix version

# Creates app folder and user
RUN mkdir /app \
    && useradd -m app \
    && chown app /app

ENV HOME /app
WORKDIR /app

ENV REPLACE_OS_VARS=true

